-- 코드를 입력하세요
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
WHERE (r.FOOD_TYPE, r.FAVORITES)  
IN (SELECT r2.FOOD_TYPE, MAX(r2.FAVORITES)
 FROM REST_INFO r2
 GROUP BY r2.FOOD_TYPE)
ORDER BY r.FOOD_TYPE DESC;